Truncate Long SQL Query
humanmade/aws-xray pull request #77
Opened 2021-01-08 09:01 UTC by ivankristianto

Fixed #74 

This PR is to ensure we truncate the long query to max 5KB. As this is enough for any accident analysis on XRay reporting.

2021-01-08 14:45 UTC, joehoyle requested changes

2021-01-08 14:45 UTC, joehoyle commented on inc/namespace.php
> + * @param int    $max_size    Maximum size, default 5KB.
```suggestion
 * @param int    $max_size    Maximum size in bytes, default 5KB.
```

2021-01-08 14:45 UTC, joehoyle commented on inc/namespace.php
> + * Truncate sql query to given max_size.
```suggestion
 * Truncate sql query to given maximum size.
```

2021-01-08 14:45 UTC, joehoyle commented on inc/namespace.php
> +function truncate_query( string $query, int $max_size = 5 * 1024, string $replacement = '…' ): string {
```suggestion
function truncate_query( string $query, int $max_size = 5 * 1024, string $replacement = '…' ) : string {
```

2021-01-08 14:45 UTC, joehoyle commented on inc/namespace.php
> +	// Truncate long query to ensure not exceed max limit.
```suggestion
	// Truncate long query to ensure it does not exceed max limit.
```

2021-01-26 21:25 UTC, joehoyle commented
@ivankristianto is this ready for re-review?

2021-01-27 02:38 UTC, ivankristianto commented
ahh yes, @joehoyle 
Sorry I forgot to mention you. This PR ready for re-review.

2021-02-02 15:57 UTC, joehoyle approved these changes

2021-02-02 15:57 UTC, merged